---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-pvc
  namespace: technitium
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi